name: nlp-poa
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310h3602819_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.12.1=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - backports.zstd=1.3.0=py310h458dff3_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py310hfff998d_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cycler=0.12.1=pyhcf101f3_2
  - datasets=4.5.0=pyhcf101f3_0
  - debugpy=1.8.20=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhcf101f3_1
  - double-conversion=3.4.0=hac47afa_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=py310had1666a_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hac47afa_2
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h5a1b470_0
  - hf-xet=1.2.1=py310hfb9af98_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=23.0.0=h7d27241_0_cuda
  - libarrow-acero=23.0.0=h7d8d6a5_0_cuda
  - libarrow-compute=23.0.0=h2db994a_0_cuda
  - libarrow-dataset=23.0.0=h7d8d6a5_0_cuda
  - libarrow-substrait=23.0.0=hf865cc0_0_cuda
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_2
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_16
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libparquet=23.0.0=h7051d1f_0_cuda
  - libpng=1.6.54=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.3=hb980946_0
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - matplotlib=3.10.8=py310h5588dad_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_455
  - multidict=6.7.0=py310hdb0e946_0
  - multiprocess=0.70.18=py310h1637853_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.2.6=py310h4987827_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - orc=2.2.2=hbd3206f_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py310hed136d8_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.47=hd2b5f0e_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.0=py310h712baa7_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py310h38315fa_0
  - psutil=7.2.2=py310h1637853_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow-core=23.0.0=py310h54c75c4_0_cuda
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.1=py310h96c60bd_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.10.19=hd8ed1ab_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py310hda3e71d_1
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pyyaml=6.0.3=py310hdb0e946_0
  - pyzmq=27.1.0=py310h535538e_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.1=h68b6638_4
  - re2=2025.11.05=ha104f34_0
  - regex=2026.1.15=py310h29418f3_0
  - requests=2.32.5=pyhcf101f3_1
  - safetensors=0.7.0=py310hf13f778_0
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.10.1=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=h3155e25_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_3
  - tokenizers=0.22.2=py310h1657867_0
  - tornado=6.5.4=py310h29418f3_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.57.6=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py310h29418f3_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xxhash=0.8.3=hbba6f48_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py310hdb0e946_0
  - zeromq=4.3.5=h5bddc39_9
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - click==8.3.1
      - cssselect==1.4.0
      - datarecorder==3.6.2
      - downloadkit==2.0.7
      - drissionpage==4.1.1.2
      - et-xmlfile==2.0.0
      - fake-useragent==2.2.0
      - greenlet==3.3.1
      - jinja2==3.1.6
      - lxml==6.0.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.4.2
      - openpyxl==3.1.5
      - playwright==1.58.0
      - pyarrow==23.0.0
      - pyee==13.0.0
      - python-dotenv==1.2.1
      - requests-file==3.0.1
      - sentence-transformers==5.2.2
      - sympy==1.14.0
      - tldextract==5.3.1
      - torch==2.10.0+cu126
      - torchvision==0.25.0+cu126
      - websocket-client==1.9.0
prefix: D:\Programs\miniconda3\envs\nlp-poa
